services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "OpenAI__ApiKey=${OpenAI__ApiKey}"
      - "OpenAI__EmbeddingModel=${OpenAI__EmbeddingModel}"
      - "Groq__ApiKey=${Groq__ApiKey}"
      - "Groq__BaseUrl=${Groq__BaseUrl}"
      - "Groq__Model=${Groq__Model}"
      - "ServiceUrls__ChromaDb=http://chromadb:8000"
      - "ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}"
    env_file:
      - .env
    volumes:
      - ./Data/Manifesten:/app/Data/Manifesten:ro
    depends_on:
      - chromadb
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: unless-stopped

volumes:
  chroma_data:
