services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OpenAI__ApiKey=${OpenAI__ApiKey}
      - OpenAI__EmbeddingModel=${OpenAI__EmbeddingModel}
      - Groq__ApiKey=${Groq__ApiKey}
      - Groq__BaseUrl=${Groq__BaseUrl}
      - Groq__Model=${Groq__Model}
      - ServiceUrls__ChromaDb=${ServiceUrls__ChromaDb}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    env_file:
      - .env
    volumes:
      - ./Data/Manifesten:/app/Data/Manifesten:ro
    restart: unless-stopped
